name: DITA Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install DITA-OT
      run: |
        wget https://github.com/dita-ot/dita-ot/releases/download/3.7.1/dita-ot-3.7.1.zip
        unzip dita-ot-3.7.1.zip
    - name: Install DITA Validator Plugin
      run: |
        dita-ot-3.7.1/bin/dita install https://github.com/jason-fox/com.here.validate.svrl/archive/master.zip
    - name: Validate DITA
      run: |
        dita-ot-3.7.1/bin/dita --format svrl-echo --input path/to/your/ditamap.ditamap
